import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Comprehensive SEO topic list for BrandVoice Studio
// 100+ topics across 3 content pillars for daily publishing

const topics = [
  // ==========================================
  // PILLAR 1: AI VIDEO MARKETING (35 topics)
  // ==========================================
  {
    title: "What is an AI Spokesperson and How Does It Work?",
    pillar: "ai-video",
    primaryKeyword: "AI spokesperson",
    secondaryKeywords: "ai video presenter, virtual spokesperson, ai avatar",
    searchIntent: "informational",
    targetAudience: "Business owners curious about AI video",
    contentAngle: "Comprehensive beginner's guide explaining the technology",
    priority: 95,
  },
  {
    title: "AI Spokesperson vs Human Presenter: Which is Better for Your Business?",
    pillar: "ai-video",
    primaryKeyword: "AI spokesperson vs human",
    secondaryKeywords: "ai video comparison, virtual presenter benefits",
    searchIntent: "informational",
    targetAudience: "Decision-makers comparing options",
    contentAngle: "Honest pros/cons comparison with use cases",
    priority: 90,
  },
  {
    title: "How Much Does an AI Spokesperson Cost? Complete Pricing Guide 2025",
    pillar: "ai-video",
    primaryKeyword: "AI spokesperson cost",
    secondaryKeywords: "ai video pricing, virtual presenter price",
    searchIntent: "transactional",
    targetAudience: "Budget-conscious business owners",
    contentAngle: "Transparent pricing breakdown with ROI analysis",
    priority: 92,
  },
  {
    title: "10 Best AI Spokesperson Tools Compared",
    pillar: "ai-video",
    primaryKeyword: "best AI spokesperson tools",
    secondaryKeywords: "ai video generator, ai presenter software",
    searchIntent: "commercial",
    targetAudience: "Business owners researching solutions",
    contentAngle: "Feature comparison with honest recommendations",
    priority: 88,
  },
  {
    title: "How to Create Professional Videos Without Being on Camera",
    pillar: "ai-video",
    primaryKeyword: "create videos without being on camera",
    secondaryKeywords: "faceless video, ai video creator",
    searchIntent: "informational",
    targetAudience: "Camera-shy business owners",
    contentAngle: "Step-by-step guide with multiple solutions",
    priority: 85,
  },
  {
    title: "AI Video Marketing Statistics: 50+ Stats You Need to Know",
    pillar: "ai-video",
    primaryKeyword: "AI video marketing statistics",
    secondaryKeywords: "video marketing stats 2025, ai content statistics",
    searchIntent: "informational",
    targetAudience: "Marketers building business cases",
    contentAngle: "Data-driven compilation with sources",
    priority: 80,
  },
  {
    title: "How to Use AI Spokespersons for Product Demonstrations",
    pillar: "ai-video",
    primaryKeyword: "AI product demo video",
    secondaryKeywords: "ai product presentation, virtual demo",
    searchIntent: "informational",
    targetAudience: "E-commerce and SaaS businesses",
    contentAngle: "Practical tutorial with examples",
    priority: 78,
  },
  {
    title: "AI Video Ads: Complete Guide to Creating High-Converting Ads",
    pillar: "ai-video",
    primaryKeyword: "AI video ads",
    secondaryKeywords: "ai advertising, automated video ads",
    searchIntent: "informational",
    targetAudience: "Advertisers and marketers",
    contentAngle: "Strategy guide with best practices",
    priority: 87,
  },
  {
    title: "The Future of Video Marketing: AI Trends for 2025 and Beyond",
    pillar: "ai-video",
    primaryKeyword: "video marketing trends 2025",
    secondaryKeywords: "ai marketing future, video marketing predictions",
    searchIntent: "informational",
    targetAudience: "Forward-thinking marketers",
    contentAngle: "Expert predictions with actionable insights",
    priority: 75,
  },
  {
    title: "How AI Spokespersons are Revolutionizing E-Learning",
    pillar: "ai-video",
    primaryKeyword: "AI spokesperson e-learning",
    secondaryKeywords: "ai training videos, virtual instructor",
    searchIntent: "informational",
    targetAudience: "Training and HR professionals",
    contentAngle: "Case studies and implementation guide",
    priority: 72,
  },
  {
    title: "Creating Multilingual Videos with AI: Reach Global Audiences",
    pillar: "ai-video",
    primaryKeyword: "AI multilingual video",
    secondaryKeywords: "ai translation video, localized video content",
    searchIntent: "informational",
    targetAudience: "International businesses",
    contentAngle: "How-to guide with language coverage",
    priority: 70,
  },
  {
    title: "AI Video Personalization: How to Create Custom Videos at Scale",
    pillar: "ai-video",
    primaryKeyword: "AI video personalization",
    secondaryKeywords: "personalized video marketing, custom ai videos",
    searchIntent: "informational",
    targetAudience: "Enterprise marketers",
    contentAngle: "Advanced strategy with tools",
    priority: 76,
  },
  {
    title: "How Real Estate Agents Use AI Video to Sell More Properties",
    pillar: "ai-video",
    primaryKeyword: "AI video real estate",
    secondaryKeywords: "real estate video marketing, ai property tours",
    searchIntent: "informational",
    targetAudience: "Real estate professionals",
    contentAngle: "Industry-specific guide with examples",
    priority: 74,
  },
  {
    title: "AI Spokespersons for Healthcare: Patient Education Videos",
    pillar: "ai-video",
    primaryKeyword: "AI healthcare video",
    secondaryKeywords: "medical ai video, patient education ai",
    searchIntent: "informational",
    targetAudience: "Healthcare providers",
    contentAngle: "HIPAA considerations and best practices",
    priority: 68,
  },
  {
    title: "How Law Firms Use AI Video for Client Communication",
    pillar: "ai-video",
    primaryKeyword: "AI video law firms",
    secondaryKeywords: "legal video marketing, attorney ai video",
    searchIntent: "informational",
    targetAudience: "Legal professionals",
    contentAngle: "Use cases and compliance considerations",
    priority: 66,
  },
  {
    title: "AI Video for Financial Services: Building Trust Digitally",
    pillar: "ai-video",
    primaryKeyword: "AI video financial services",
    secondaryKeywords: "fintech video marketing, ai banking videos",
    searchIntent: "informational",
    targetAudience: "Financial advisors and fintech",
    contentAngle: "Trust-building strategies with AI",
    priority: 67,
  },
  {
    title: "Creating AI Testimonial Videos That Convert",
    pillar: "ai-video",
    primaryKeyword: "AI testimonial video",
    secondaryKeywords: "video testimonials, customer review videos",
    searchIntent: "informational",
    targetAudience: "Marketers needing social proof",
    contentAngle: "Ethical considerations and best practices",
    priority: 73,
  },
  {
    title: "AI Video Scripts: How to Write Copy That Converts",
    pillar: "ai-video",
    primaryKeyword: "AI video script writing",
    secondaryKeywords: "video copywriting, ai script generator",
    searchIntent: "informational",
    targetAudience: "Content creators and marketers",
    contentAngle: "Framework and templates",
    priority: 79,
  },
  {
    title: "Measuring AI Video ROI: Metrics That Matter",
    pillar: "ai-video",
    primaryKeyword: "AI video ROI",
    secondaryKeywords: "video marketing metrics, ai video analytics",
    searchIntent: "informational",
    targetAudience: "Marketing managers",
    contentAngle: "KPIs and tracking guide",
    priority: 77,
  },
  {
    title: "AI Video Quality: How to Ensure Professional Results",
    pillar: "ai-video",
    primaryKeyword: "AI video quality",
    secondaryKeywords: "professional ai video, video production quality",
    searchIntent: "informational",
    targetAudience: "Quality-conscious businesses",
    contentAngle: "Technical guide and best practices",
    priority: 71,
  },
  {
    title: "AI Spokesperson Voice Cloning: What You Need to Know",
    pillar: "ai-video",
    primaryKeyword: "AI voice cloning",
    secondaryKeywords: "ai voice generator, synthetic voice",
    searchIntent: "informational",
    targetAudience: "Tech-curious marketers",
    contentAngle: "Technology explanation and ethics",
    priority: 69,
  },
  {
    title: "How to A/B Test AI Video Ads for Maximum Performance",
    pillar: "ai-video",
    primaryKeyword: "A/B test video ads",
    secondaryKeywords: "video ad testing, optimize video ads",
    searchIntent: "informational",
    targetAudience: "Performance marketers",
    contentAngle: "Testing framework and case studies",
    priority: 75,
  },
  {
    title: "AI Video for SaaS: Onboarding and Feature Explainers",
    pillar: "ai-video",
    primaryKeyword: "AI video SaaS",
    secondaryKeywords: "saas onboarding video, product explainer ai",
    searchIntent: "informational",
    targetAudience: "SaaS companies",
    contentAngle: "Use cases and implementation",
    priority: 72,
  },
  {
    title: "Creating FAQ Videos with AI: Scale Customer Support",
    pillar: "ai-video",
    primaryKeyword: "AI FAQ video",
    secondaryKeywords: "video customer support, ai help videos",
    searchIntent: "informational",
    targetAudience: "Customer success teams",
    contentAngle: "Efficiency and cost savings focus",
    priority: 70,
  },
  {
    title: "AI Video for Nonprofits: Amplify Your Mission",
    pillar: "ai-video",
    primaryKeyword: "AI video nonprofit",
    secondaryKeywords: "nonprofit video marketing, charity ai video",
    searchIntent: "informational",
    targetAudience: "Nonprofit organizations",
    contentAngle: "Budget-friendly strategies",
    priority: 65,
  },
  {
    title: "How Coaches and Consultants Use AI Video to Scale",
    pillar: "ai-video",
    primaryKeyword: "AI video coaches",
    secondaryKeywords: "consultant video marketing, coaching ai video",
    searchIntent: "informational",
    targetAudience: "Coaches and consultants",
    contentAngle: "Scaling personal brand with AI",
    priority: 74,
  },
  {
    title: "AI Video SEO: Optimizing Videos for Search Rankings",
    pillar: "ai-video",
    primaryKeyword: "video SEO",
    secondaryKeywords: "optimize video search, youtube seo ai",
    searchIntent: "informational",
    targetAudience: "SEO professionals",
    contentAngle: "Technical SEO guide for video",
    priority: 78,
  },
  {
    title: "The Psychology Behind Why AI Videos Convert Better",
    pillar: "ai-video",
    primaryKeyword: "video conversion psychology",
    secondaryKeywords: "why video converts, video marketing psychology",
    searchIntent: "informational",
    targetAudience: "Marketing strategists",
    contentAngle: "Science-backed insights",
    priority: 73,
  },
  {
    title: "AI Video Accessibility: Captions, Audio Description, and More",
    pillar: "ai-video",
    primaryKeyword: "AI video accessibility",
    secondaryKeywords: "video captions ai, accessible video content",
    searchIntent: "informational",
    targetAudience: "Compliance-focused businesses",
    contentAngle: "ADA compliance and best practices",
    priority: 68,
  },
  {
    title: "From Script to Screen: AI Video Production Workflow",
    pillar: "ai-video",
    primaryKeyword: "AI video production workflow",
    secondaryKeywords: "video creation process, ai video pipeline",
    searchIntent: "informational",
    targetAudience: "Production teams",
    contentAngle: "End-to-end process guide",
    priority: 71,
  },
  {
    title: "AI Video Branding: Maintaining Consistency Across Content",
    pillar: "ai-video",
    primaryKeyword: "AI video branding",
    secondaryKeywords: "video brand consistency, branded ai video",
    searchIntent: "informational",
    targetAudience: "Brand managers",
    contentAngle: "Brand guidelines for AI video",
    priority: 69,
  },
  {
    title: "Common AI Video Mistakes and How to Avoid Them",
    pillar: "ai-video",
    primaryKeyword: "AI video mistakes",
    secondaryKeywords: "video marketing errors, ai content mistakes",
    searchIntent: "informational",
    targetAudience: "New AI video users",
    contentAngle: "Troubleshooting guide",
    priority: 76,
  },
  {
    title: "AI Video for Recruitment: Attract Top Talent",
    pillar: "ai-video",
    primaryKeyword: "AI recruitment video",
    secondaryKeywords: "hiring video ai, employer branding video",
    searchIntent: "informational",
    targetAudience: "HR professionals",
    contentAngle: "Employer branding strategies",
    priority: 67,
  },
  {
    title: "Interactive AI Videos: The Next Frontier",
    pillar: "ai-video",
    primaryKeyword: "interactive AI video",
    secondaryKeywords: "clickable video, interactive video marketing",
    searchIntent: "informational",
    targetAudience: "Innovation-focused marketers",
    contentAngle: "Emerging technology guide",
    priority: 66,
  },
  {
    title: "AI Video Analytics: Understanding Viewer Behavior",
    pillar: "ai-video",
    primaryKeyword: "video analytics",
    secondaryKeywords: "video engagement metrics, viewer behavior analytics",
    searchIntent: "informational",
    targetAudience: "Data-driven marketers",
    contentAngle: "Analytics deep-dive",
    priority: 74,
  },

  // ==========================================
  // PILLAR 2: BUSINESS GROWTH (35 topics)
  // ==========================================
  {
    title: "Content Marketing ROI: How to Calculate and Improve It",
    pillar: "business-growth",
    primaryKeyword: "content marketing ROI",
    secondaryKeywords: "marketing roi calculator, content roi metrics",
    searchIntent: "informational",
    targetAudience: "Marketing managers",
    contentAngle: "Formulas and improvement strategies",
    priority: 85,
  },
  {
    title: "Marketing Automation for Small Business: Complete Guide",
    pillar: "business-growth",
    primaryKeyword: "marketing automation small business",
    secondaryKeywords: "automated marketing, small business automation",
    searchIntent: "informational",
    targetAudience: "Small business owners",
    contentAngle: "Affordable tools and strategies",
    priority: 88,
  },
  {
    title: "How to Scale Your Service Business with Digital Marketing",
    pillar: "business-growth",
    primaryKeyword: "scale service business",
    secondaryKeywords: "service business marketing, grow service company",
    searchIntent: "informational",
    targetAudience: "Service business owners",
    contentAngle: "Growth playbook",
    priority: 82,
  },
  {
    title: "Customer Acquisition Cost: Benchmarks and Optimization",
    pillar: "business-growth",
    primaryKeyword: "customer acquisition cost",
    secondaryKeywords: "CAC optimization, reduce acquisition cost",
    searchIntent: "informational",
    targetAudience: "Growth-focused businesses",
    contentAngle: "Industry benchmarks and strategies",
    priority: 80,
  },
  {
    title: "Building a Content Engine: Systems for Consistent Publishing",
    pillar: "business-growth",
    primaryKeyword: "content engine",
    secondaryKeywords: "content system, consistent content publishing",
    searchIntent: "informational",
    targetAudience: "Content marketers",
    contentAngle: "Systems and workflows",
    priority: 78,
  },
  {
    title: "Lead Generation Strategies That Actually Work in 2025",
    pillar: "business-growth",
    primaryKeyword: "lead generation strategies",
    secondaryKeywords: "generate leads, lead gen tactics",
    searchIntent: "informational",
    targetAudience: "Sales and marketing teams",
    contentAngle: "Proven tactics with examples",
    priority: 90,
  },
  {
    title: "How to Build a Personal Brand That Drives Business",
    pillar: "business-growth",
    primaryKeyword: "personal brand business",
    secondaryKeywords: "build personal brand, personal branding",
    searchIntent: "informational",
    targetAudience: "Entrepreneurs and executives",
    contentAngle: "Step-by-step brand building",
    priority: 84,
  },
  {
    title: "Email Marketing Automation: Sequences That Convert",
    pillar: "business-growth",
    primaryKeyword: "email marketing automation",
    secondaryKeywords: "email sequences, automated email marketing",
    searchIntent: "informational",
    targetAudience: "Email marketers",
    contentAngle: "Templates and workflows",
    priority: 83,
  },
  {
    title: "How to Create a Marketing Funnel That Converts",
    pillar: "business-growth",
    primaryKeyword: "marketing funnel",
    secondaryKeywords: "sales funnel, conversion funnel",
    searchIntent: "informational",
    targetAudience: "Digital marketers",
    contentAngle: "Funnel architecture guide",
    priority: 86,
  },
  {
    title: "Customer Lifetime Value: Calculate and Increase CLV",
    pillar: "business-growth",
    primaryKeyword: "customer lifetime value",
    secondaryKeywords: "CLV calculation, increase customer value",
    searchIntent: "informational",
    targetAudience: "Business strategists",
    contentAngle: "Formulas and growth tactics",
    priority: 79,
  },
  {
    title: "Brand Storytelling: Connect with Customers Emotionally",
    pillar: "business-growth",
    primaryKeyword: "brand storytelling",
    secondaryKeywords: "brand narrative, emotional branding",
    searchIntent: "informational",
    targetAudience: "Brand marketers",
    contentAngle: "Framework and examples",
    priority: 77,
  },
  {
    title: "Local SEO for Service Businesses: Dominate Your Market",
    pillar: "business-growth",
    primaryKeyword: "local SEO service business",
    secondaryKeywords: "local search optimization, local business seo",
    searchIntent: "informational",
    targetAudience: "Local service businesses",
    contentAngle: "Tactical guide",
    priority: 85,
  },
  {
    title: "How to Price Your Services for Maximum Profit",
    pillar: "business-growth",
    primaryKeyword: "pricing services",
    secondaryKeywords: "service pricing strategy, price your work",
    searchIntent: "informational",
    targetAudience: "Service providers",
    contentAngle: "Pricing psychology and models",
    priority: 81,
  },
  {
    title: "Referral Marketing: Build a System That Generates Leads",
    pillar: "business-growth",
    primaryKeyword: "referral marketing",
    secondaryKeywords: "referral program, word of mouth marketing",
    searchIntent: "informational",
    targetAudience: "Business owners",
    contentAngle: "Program design and incentives",
    priority: 76,
  },
  {
    title: "Content Repurposing: Get More from Every Piece",
    pillar: "business-growth",
    primaryKeyword: "content repurposing",
    secondaryKeywords: "repurpose content, content recycling",
    searchIntent: "informational",
    targetAudience: "Content marketers",
    contentAngle: "Workflow and tools",
    priority: 79,
  },
  {
    title: "Social Proof Marketing: Leverage Reviews and Testimonials",
    pillar: "business-growth",
    primaryKeyword: "social proof marketing",
    secondaryKeywords: "testimonial marketing, reviews strategy",
    searchIntent: "informational",
    targetAudience: "All businesses",
    contentAngle: "Psychology and implementation",
    priority: 78,
  },
  {
    title: "How to Create an Irresistible Offer",
    pillar: "business-growth",
    primaryKeyword: "create irresistible offer",
    secondaryKeywords: "offer creation, value proposition",
    searchIntent: "informational",
    targetAudience: "Entrepreneurs",
    contentAngle: "Framework and examples",
    priority: 82,
  },
  {
    title: "Marketing Budget Allocation: Where to Invest",
    pillar: "business-growth",
    primaryKeyword: "marketing budget allocation",
    secondaryKeywords: "marketing spend, budget planning marketing",
    searchIntent: "informational",
    targetAudience: "Marketing managers",
    contentAngle: "Data-driven recommendations",
    priority: 75,
  },
  {
    title: "Conversion Rate Optimization: Double Your Conversions",
    pillar: "business-growth",
    primaryKeyword: "conversion rate optimization",
    secondaryKeywords: "CRO strategies, improve conversions",
    searchIntent: "informational",
    targetAudience: "Digital marketers",
    contentAngle: "Testing framework",
    priority: 84,
  },
  {
    title: "Competitor Analysis: Learn from Your Competition",
    pillar: "business-growth",
    primaryKeyword: "competitor analysis",
    secondaryKeywords: "competitive analysis, market research",
    searchIntent: "informational",
    targetAudience: "Business strategists",
    contentAngle: "Tools and methodology",
    priority: 74,
  },
  {
    title: "Niching Down: Why Specialization Wins",
    pillar: "business-growth",
    primaryKeyword: "niche marketing",
    secondaryKeywords: "business specialization, niche down",
    searchIntent: "informational",
    targetAudience: "Generalist businesses",
    contentAngle: "Case studies and strategy",
    priority: 76,
  },
  {
    title: "Building Trust Online: Credibility Signals That Convert",
    pillar: "business-growth",
    primaryKeyword: "build trust online",
    secondaryKeywords: "online credibility, trust signals",
    searchIntent: "informational",
    targetAudience: "Online businesses",
    contentAngle: "Trust element checklist",
    priority: 77,
  },
  {
    title: "Customer Retention Strategies: Keep More Customers",
    pillar: "business-growth",
    primaryKeyword: "customer retention strategies",
    secondaryKeywords: "retain customers, reduce churn",
    searchIntent: "informational",
    targetAudience: "Customer success teams",
    contentAngle: "Proven retention tactics",
    priority: 80,
  },
  {
    title: "How to Launch a New Product Successfully",
    pillar: "business-growth",
    primaryKeyword: "product launch strategy",
    secondaryKeywords: "launch new product, product launch plan",
    searchIntent: "informational",
    targetAudience: "Product managers",
    contentAngle: "Launch checklist and timeline",
    priority: 78,
  },
  {
    title: "Upselling and Cross-Selling: Increase Revenue Per Customer",
    pillar: "business-growth",
    primaryKeyword: "upselling cross-selling",
    secondaryKeywords: "increase average order, upsell strategies",
    searchIntent: "informational",
    targetAudience: "Sales teams",
    contentAngle: "Techniques and scripts",
    priority: 75,
  },
  {
    title: "Building a Marketing Team: Hire vs Outsource",
    pillar: "business-growth",
    primaryKeyword: "build marketing team",
    secondaryKeywords: "hire marketers, outsource marketing",
    searchIntent: "informational",
    targetAudience: "Business owners scaling",
    contentAngle: "Decision framework",
    priority: 72,
  },
  {
    title: "How to Write a Value Proposition That Sells",
    pillar: "business-growth",
    primaryKeyword: "value proposition",
    secondaryKeywords: "unique value proposition, uvp marketing",
    searchIntent: "informational",
    targetAudience: "Marketers and founders",
    contentAngle: "Formula and examples",
    priority: 81,
  },
  {
    title: "Marketing Metrics That Matter: What to Track",
    pillar: "business-growth",
    primaryKeyword: "marketing metrics",
    secondaryKeywords: "marketing KPIs, track marketing performance",
    searchIntent: "informational",
    targetAudience: "Marketing managers",
    contentAngle: "Essential metrics guide",
    priority: 79,
  },
  {
    title: "Content Calendar Creation: Plan a Year of Content",
    pillar: "business-growth",
    primaryKeyword: "content calendar",
    secondaryKeywords: "editorial calendar, content planning",
    searchIntent: "informational",
    targetAudience: "Content teams",
    contentAngle: "Templates and strategy",
    priority: 77,
  },
  {
    title: "Landing Page Optimization: Elements of High-Converting Pages",
    pillar: "business-growth",
    primaryKeyword: "landing page optimization",
    secondaryKeywords: "landing page best practices, optimize landing page",
    searchIntent: "informational",
    targetAudience: "Digital marketers",
    contentAngle: "Design principles and testing",
    priority: 83,
  },
  {
    title: "How to Get More Reviews and Testimonials",
    pillar: "business-growth",
    primaryKeyword: "get more reviews",
    secondaryKeywords: "collect testimonials, review generation",
    searchIntent: "informational",
    targetAudience: "All businesses",
    contentAngle: "Outreach templates and timing",
    priority: 78,
  },
  {
    title: "Thought Leadership: Position Yourself as an Expert",
    pillar: "business-growth",
    primaryKeyword: "thought leadership",
    secondaryKeywords: "become industry expert, authority building",
    searchIntent: "informational",
    targetAudience: "Executives and founders",
    contentAngle: "Content strategy for authority",
    priority: 74,
  },
  {
    title: "Marketing for Introverts: Strategies That Feel Natural",
    pillar: "business-growth",
    primaryKeyword: "marketing for introverts",
    secondaryKeywords: "introvert entrepreneur, quiet marketing",
    searchIntent: "informational",
    targetAudience: "Introverted business owners",
    contentAngle: "Authentic approaches",
    priority: 70,
  },
  {
    title: "Seasonal Marketing: Capitalize on Key Dates",
    pillar: "business-growth",
    primaryKeyword: "seasonal marketing",
    secondaryKeywords: "holiday marketing, seasonal campaigns",
    searchIntent: "informational",
    targetAudience: "Retail and e-commerce",
    contentAngle: "Calendar and campaign ideas",
    priority: 73,
  },
  {
    title: "How to Write Case Studies That Win Clients",
    pillar: "business-growth",
    primaryKeyword: "write case studies",
    secondaryKeywords: "case study template, client case studies",
    searchIntent: "informational",
    targetAudience: "B2B marketers",
    contentAngle: "Template and storytelling",
    priority: 76,
  },

  // ==========================================
  // PILLAR 3: PLATFORM STRATEGY (35 topics)
  // ==========================================
  {
    title: "Instagram Reels Algorithm: How to Get More Views",
    pillar: "platform-strategy",
    primaryKeyword: "Instagram Reels algorithm",
    secondaryKeywords: "reels views, instagram algorithm 2025",
    searchIntent: "informational",
    targetAudience: "Instagram marketers",
    contentAngle: "Algorithm breakdown and tactics",
    priority: 90,
  },
  {
    title: "TikTok for Business: Complete Marketing Guide",
    pillar: "platform-strategy",
    primaryKeyword: "TikTok for business",
    secondaryKeywords: "tiktok marketing, business tiktok strategy",
    searchIntent: "informational",
    targetAudience: "Businesses new to TikTok",
    contentAngle: "Comprehensive starter guide",
    priority: 92,
  },
  {
    title: "YouTube Shorts vs TikTok vs Reels: Which to Choose?",
    pillar: "platform-strategy",
    primaryKeyword: "YouTube Shorts vs TikTok",
    secondaryKeywords: "short form video comparison, reels vs tiktok",
    searchIntent: "informational",
    targetAudience: "Video content creators",
    contentAngle: "Platform comparison with data",
    priority: 88,
  },
  {
    title: "LinkedIn Video Marketing: Stand Out in the Feed",
    pillar: "platform-strategy",
    primaryKeyword: "LinkedIn video marketing",
    secondaryKeywords: "linkedin video, b2b video linkedin",
    searchIntent: "informational",
    targetAudience: "B2B marketers",
    contentAngle: "Professional video strategy",
    priority: 85,
  },
  {
    title: "Best Times to Post on Social Media in 2025",
    pillar: "platform-strategy",
    primaryKeyword: "best times to post social media",
    secondaryKeywords: "posting times, optimal post timing",
    searchIntent: "informational",
    targetAudience: "Social media managers",
    contentAngle: "Data-backed recommendations",
    priority: 86,
  },
  {
    title: "How to Go Viral on TikTok: Proven Strategies",
    pillar: "platform-strategy",
    primaryKeyword: "go viral TikTok",
    secondaryKeywords: "viral tiktok, tiktok viral strategy",
    searchIntent: "informational",
    targetAudience: "TikTok creators",
    contentAngle: "Viral mechanics and examples",
    priority: 89,
  },
  {
    title: "Facebook Video Ads: Complete Setup and Optimization Guide",
    pillar: "platform-strategy",
    primaryKeyword: "Facebook video ads",
    secondaryKeywords: "fb video advertising, facebook ad video",
    searchIntent: "informational",
    targetAudience: "Facebook advertisers",
    contentAngle: "Step-by-step setup guide",
    priority: 84,
  },
  {
    title: "Pinterest Video Marketing: Untapped Opportunity",
    pillar: "platform-strategy",
    primaryKeyword: "Pinterest video marketing",
    secondaryKeywords: "pinterest video pins, video on pinterest",
    searchIntent: "informational",
    targetAudience: "E-commerce and lifestyle brands",
    contentAngle: "Platform-specific strategies",
    priority: 75,
  },
  {
    title: "Social Media Video Specs: 2025 Size Guide",
    pillar: "platform-strategy",
    primaryKeyword: "social media video sizes",
    secondaryKeywords: "video dimensions, social video specs",
    searchIntent: "informational",
    targetAudience: "Content creators",
    contentAngle: "Comprehensive specs reference",
    priority: 82,
  },
  {
    title: "How to Build a TikTok Content Strategy",
    pillar: "platform-strategy",
    primaryKeyword: "TikTok content strategy",
    secondaryKeywords: "tiktok strategy, plan tiktok content",
    searchIntent: "informational",
    targetAudience: "Brand marketers",
    contentAngle: "Strategy framework",
    priority: 87,
  },
  {
    title: "Instagram Story Ideas That Drive Engagement",
    pillar: "platform-strategy",
    primaryKeyword: "Instagram Story ideas",
    secondaryKeywords: "story content ideas, instagram stories",
    searchIntent: "informational",
    targetAudience: "Instagram users",
    contentAngle: "Creative inspiration list",
    priority: 80,
  },
  {
    title: "YouTube SEO: Rank Your Videos Higher",
    pillar: "platform-strategy",
    primaryKeyword: "YouTube SEO",
    secondaryKeywords: "youtube ranking, video seo youtube",
    searchIntent: "informational",
    targetAudience: "YouTube creators",
    contentAngle: "Optimization checklist",
    priority: 86,
  },
  {
    title: "TikTok Hashtag Strategy: What Works in 2025",
    pillar: "platform-strategy",
    primaryKeyword: "TikTok hashtags",
    secondaryKeywords: "tiktok hashtag strategy, hashtags tiktok",
    searchIntent: "informational",
    targetAudience: "TikTok creators",
    contentAngle: "Research and best practices",
    priority: 83,
  },
  {
    title: "Cross-Platform Video Strategy: Repurpose Content Effectively",
    pillar: "platform-strategy",
    primaryKeyword: "cross-platform video",
    secondaryKeywords: "repurpose video content, multi-platform video",
    searchIntent: "informational",
    targetAudience: "Social media managers",
    contentAngle: "Workflow and adaptations",
    priority: 81,
  },
  {
    title: "How Often to Post on Each Social Platform",
    pillar: "platform-strategy",
    primaryKeyword: "how often post social media",
    secondaryKeywords: "posting frequency, social media schedule",
    searchIntent: "informational",
    targetAudience: "Social media managers",
    contentAngle: "Platform-by-platform guide",
    priority: 79,
  },
  {
    title: "TikTok Ads for Beginners: Getting Started Guide",
    pillar: "platform-strategy",
    primaryKeyword: "TikTok ads beginners",
    secondaryKeywords: "tiktok advertising, start tiktok ads",
    searchIntent: "informational",
    targetAudience: "Advertisers new to TikTok",
    contentAngle: "Step-by-step tutorial",
    priority: 85,
  },
  {
    title: "Instagram Reels vs Stories: When to Use Each",
    pillar: "platform-strategy",
    primaryKeyword: "Reels vs Stories",
    secondaryKeywords: "instagram reels stories, reels or stories",
    searchIntent: "informational",
    targetAudience: "Instagram creators",
    contentAngle: "Use case comparison",
    priority: 78,
  },
  {
    title: "YouTube Thumbnail Design: Click-Worthy Images",
    pillar: "platform-strategy",
    primaryKeyword: "YouTube thumbnail design",
    secondaryKeywords: "thumbnail best practices, youtube thumbnails",
    searchIntent: "informational",
    targetAudience: "YouTube creators",
    contentAngle: "Design principles and tools",
    priority: 80,
  },
  {
    title: "How to Use Trending Sounds on TikTok and Reels",
    pillar: "platform-strategy",
    primaryKeyword: "trending sounds TikTok",
    secondaryKeywords: "viral sounds, trending audio reels",
    searchIntent: "informational",
    targetAudience: "Short-form creators",
    contentAngle: "Finding and using trends",
    priority: 82,
  },
  {
    title: "Social Media Analytics: What the Numbers Mean",
    pillar: "platform-strategy",
    primaryKeyword: "social media analytics",
    secondaryKeywords: "social media metrics, analyze social data",
    searchIntent: "informational",
    targetAudience: "Social media managers",
    contentAngle: "Metrics interpretation guide",
    priority: 77,
  },
  {
    title: "Building Community on Social Media: Engagement Tactics",
    pillar: "platform-strategy",
    primaryKeyword: "social media community",
    secondaryKeywords: "build community online, engagement tactics",
    searchIntent: "informational",
    targetAudience: "Community managers",
    contentAngle: "Community building strategies",
    priority: 76,
  },
  {
    title: "TikTok Duets and Stitches: Creative Collaboration",
    pillar: "platform-strategy",
    primaryKeyword: "TikTok duet stitch",
    secondaryKeywords: "duet feature, tiktok stitch",
    searchIntent: "informational",
    targetAudience: "TikTok creators",
    contentAngle: "Feature tutorial and ideas",
    priority: 74,
  },
  {
    title: "Video Content Ideas for Every Day of the Week",
    pillar: "platform-strategy",
    primaryKeyword: "video content ideas",
    secondaryKeywords: "video ideas, content inspiration video",
    searchIntent: "informational",
    targetAudience: "Content creators",
    contentAngle: "Daily posting framework",
    priority: 81,
  },
  {
    title: "How to Create Carousel Posts That Get Saved",
    pillar: "platform-strategy",
    primaryKeyword: "Instagram carousel posts",
    secondaryKeywords: "carousel content, slide posts instagram",
    searchIntent: "informational",
    targetAudience: "Instagram creators",
    contentAngle: "Design and content tips",
    priority: 75,
  },
  {
    title: "Growing on YouTube in 2025: What Works Now",
    pillar: "platform-strategy",
    primaryKeyword: "grow YouTube 2025",
    secondaryKeywords: "youtube growth, grow youtube channel",
    searchIntent: "informational",
    targetAudience: "YouTube creators",
    contentAngle: "Updated strategies",
    priority: 84,
  },
  {
    title: "Social Media Hooks: Stop the Scroll in 3 Seconds",
    pillar: "platform-strategy",
    primaryKeyword: "social media hooks",
    secondaryKeywords: "video hooks, stop scroll content",
    searchIntent: "informational",
    targetAudience: "Content creators",
    contentAngle: "Hook formulas and examples",
    priority: 85,
  },
  {
    title: "LinkedIn Live: How to Host Successful Broadcasts",
    pillar: "platform-strategy",
    primaryKeyword: "LinkedIn Live",
    secondaryKeywords: "linkedin streaming, linkedin live video",
    searchIntent: "informational",
    targetAudience: "B2B professionals",
    contentAngle: "Setup and best practices",
    priority: 72,
  },
  {
    title: "Twitter/X Video Strategy: What's Working Now",
    pillar: "platform-strategy",
    primaryKeyword: "Twitter video strategy",
    secondaryKeywords: "x video marketing, twitter video",
    searchIntent: "informational",
    targetAudience: "Twitter/X users",
    contentAngle: "Platform-specific tactics",
    priority: 73,
  },
  {
    title: "Social Media Scheduling: Best Tools and Practices",
    pillar: "platform-strategy",
    primaryKeyword: "social media scheduling",
    secondaryKeywords: "schedule posts, social media tools",
    searchIntent: "informational",
    targetAudience: "Social media managers",
    contentAngle: "Tool comparison and workflow",
    priority: 78,
  },
  {
    title: "How to Handle Negative Comments on Social Media",
    pillar: "platform-strategy",
    primaryKeyword: "negative comments social media",
    secondaryKeywords: "handle trolls, respond negative feedback",
    searchIntent: "informational",
    targetAudience: "Brand managers",
    contentAngle: "Response templates and strategy",
    priority: 74,
  },
  {
    title: "User-Generated Content: Turn Customers into Creators",
    pillar: "platform-strategy",
    primaryKeyword: "user-generated content",
    secondaryKeywords: "UGC marketing, customer content",
    searchIntent: "informational",
    targetAudience: "Brand marketers",
    contentAngle: "UGC campaign strategies",
    priority: 79,
  },
  {
    title: "Influencer Marketing: Find and Partner with Creators",
    pillar: "platform-strategy",
    primaryKeyword: "influencer marketing",
    secondaryKeywords: "influencer partnerships, creator collaboration",
    searchIntent: "informational",
    targetAudience: "Brand marketers",
    contentAngle: "Partnership framework",
    priority: 80,
  },
  {
    title: "Social Media Crisis Management: Be Prepared",
    pillar: "platform-strategy",
    primaryKeyword: "social media crisis",
    secondaryKeywords: "crisis management social, pr crisis social",
    searchIntent: "informational",
    targetAudience: "PR and brand teams",
    contentAngle: "Crisis playbook",
    priority: 71,
  },
  {
    title: "Platform Algorithm Updates: What Changed Recently",
    pillar: "platform-strategy",
    primaryKeyword: "social media algorithm updates",
    secondaryKeywords: "algorithm changes, platform updates",
    searchIntent: "informational",
    targetAudience: "Social media managers",
    contentAngle: "Latest changes roundup",
    priority: 83,
  },
  {
    title: "Social Media for B2B: Platforms That Drive Leads",
    pillar: "platform-strategy",
    primaryKeyword: "B2B social media",
    secondaryKeywords: "b2b social strategy, social media b2b marketing",
    searchIntent: "informational",
    targetAudience: "B2B marketers",
    contentAngle: "Platform recommendations",
    priority: 77,
  },
];

async function main() {
  console.log('Seeding blog topics...');

  // Calculate scheduled dates starting from tomorrow
  const startDate = new Date();
  startDate.setDate(startDate.getDate() + 1);
  startDate.setHours(9, 0, 0, 0); // 9 AM

  // Sort topics by priority (highest first)
  const sortedTopics = [...topics].sort((a, b) => b.priority - a.priority);

  let createdCount = 0;
  let skippedCount = 0;

  for (let i = 0; i < sortedTopics.length; i++) {
    const topic = sortedTopics[i];
    const scheduledDate = new Date(startDate);
    scheduledDate.setDate(scheduledDate.getDate() + i);

    // Check if topic already exists
    const existing = await prisma.blogTopic.findFirst({
      where: { title: topic.title }
    });

    if (existing) {
      console.log(`Skipping existing: ${topic.title}`);
      skippedCount++;
      continue;
    }

    await prisma.blogTopic.create({
      data: {
        title: topic.title,
        pillar: topic.pillar,
        primaryKeyword: topic.primaryKeyword,
        secondaryKeywords: topic.secondaryKeywords || null,
        searchIntent: topic.searchIntent,
        targetAudience: topic.targetAudience || null,
        contentAngle: topic.contentAngle || null,
        priority: topic.priority,
        scheduledFor: scheduledDate,
        status: 'queued',
      },
    });

    createdCount++;
    console.log(`Created: ${topic.title} (scheduled: ${scheduledDate.toDateString()})`);
  }

  console.log(`\nSeeding complete!`);
  console.log(`Created: ${createdCount} topics`);
  console.log(`Skipped: ${skippedCount} existing topics`);
  console.log(`Total in queue: ${topics.length} topics (${Math.ceil(topics.length / 7)} weeks of daily content)`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
